export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_POSTS_PENDING = 'FETCH_POSTS_PENDING'
export const FETCH_POSTS_FULFILLED = 'FETCH_POSTS_FULFILLED'
export const FETCH_POSTS_REJECTED = 'FETCH_POSTS_REJECTED'

export const CREATE_POST = 'CREATE_POST'
export const CREATE_POST_PENDING = 'CREATE_POST_PENDING'
export const CREATE_POST_FULFILLED = 'CREATE_POST_FULFILLED'
export const CREATE_POST_REJECTED = 'CREATE_POST_REJECTED'

export const DELETE_POST = 'DELETE_POST'
export const DELETE_POST_PENDING = 'DELETE_POST_PENDING'
export const DELETE_POST_FULFILLED = 'DELETE_POST_FULFILLED'
export const DELETE_POST_REJECTED = 'DELETE_POST_REJECTED'

export const SIGN_IN = 'SIGN_IN'
export const SIGN_IN_PENDING = 'SIGN_IN_PENDING'
export const SIGN_IN_FULFILLED = 'SIGN_IN_FULFILLED'
export const SIGN_IN_REJECTED = 'SIGN_IN_REJECTED'

export const SIGN_OUT = 'SIGN_OUT'
export const SIGN_OUT_PENDING = 'SIGN_OUT_PENDING'
export const SIGN_OUT_FULFILLED = 'SIGN_OUT_FULFILLED'
export const SIGN_OUT_REJECTED = 'SIGN_OUT_REJECTED'

export const CREATE_AUTH = 'CREATE_AUTH'
export const CREATE_AUTH_PENDING = 'CREATE_AUTH_PENDING'
export const CREATE_AUTH_FULFILLED = 'CREATE_AUTH_FULFILLED'
export const CREATE_AUTH_REJECTED = 'CREATE_AUTH_REJECTED'

export const GET_AUTH = 'GET_AUTH'
export const GET_AUTH_PENDING = 'GET_AUTH_PENDING'
export const GET_AUTH_FULFILLED = 'GET_AUTH_FULFILLED'
export const GET_AUTH_REJECTED = 'GET_AUTH_REJECTED'