export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_POSTS_PENDING = 'FETCH_POSTS_PENDING'
export const FETCH_POSTS_FULFILLED = 'FETCH_POSTS_FULFILLED'
export const FETCH_POSTS_REJECTED = 'FETCH_POSTS_REJECTED'

export const CREATE_POST = 'CREATE_POST'
export const CREATE_POST_PENDING = 'CREATE_POST_PENDING'
export const CREATE_POST_FULFILLED = 'CREATE_POST_FULFILLED'
export const CREATE_POST_REJECTED = 'CREATE_POST_REJECTED'

export const DELETE_POST = 'DELETE_POST'
export const DELETE_POST_PENDING = 'DELETE_POST_PENDING'
export const DELETE_POST_FULFILLED = 'DELETE_POST_FULFILLED'
export const DELETE_POST_REJECTED = 'DELETE_POST_REJECTED'

export const SIGN_IN = 'SIGN_IN'
export const SIGN_IN_PENDING = 'SIGN_IN_PENDING'
export const SIGN_IN_FULFILLED = 'SIGN_IN_FULFILLED'
export const SIGN_IN_REJECTED = 'SIGN_IN_REJECTED'

export const SIGN_OUT = 'SIGN_OUT'
export const SIGN_OUT_PENDING = 'SIGN_OUT_PENDING'
export const SIGN_OUT_FULFILLED = 'SIGN_OUT_FULFILLED'
export const SIGN_OUT_REJECTED = 'SIGN_OUT_REJECTED'

export const CREATE_USER = 'CREATE_USER'
export const CREATE_USER_PENDING = 'CREATE_USER_PENDING'
export const CREATE_USER_FULFILLED = 'CREATE_USER_FULFILLED'
export const CREATE_USER_REJECTED = 'CREATE_USER_REJECTED'

export const DELETE_USER = 'DELETE_USER'
export const DELETE_USER_PENDING = 'DELETE_USER_PENDING'
export const DELETE_USER_FULFILLED = 'DELETE_USER_FULFILLED'
export const DELETE_USER_REJECTED = 'DELETE_USER_REJECTED'

export const ROUTE_CHANGE = 'ROUTE_CHANGE'
export const ROUTE_CHANGE_PENDING = 'ROUTE_CHANGE_PENDING'
export const ROUTE_CHANGE_FULFILLED = 'ROUTE_CHANGE_FULFILLED'
export const ROUTE_CHANGE_REJECTED = 'ROUTE_CHANGE_REJECTED'

// @todo should get a refreshed token